### ISSUE TITLE
Register on server

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#1]
When opened for the first time request a `userID` from the server. (See Server API).

**Comment by ADimeo** [comment]
This has a dependency on #7

**Comment by ADimeo** [comment]
Also has a dependency on the server actually running, which I don't think it's doing at the moment.

**Comment by ADimeo** [comment]
@EatingBacon said he'd have the server running in the next few days, so I'll review this issue then.

**Comment by ADimeo** [comment]
With the bot online this functionality was tested manually, and works.
