### ISSUE TITLE
Implement Permission and DataTheft Methods from IApp in MainActivity

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#14]
```    
hasPermission(int)
getCalendarEvents()
getContacts()
getLocation()
```

**Comment by ADimeo** [comment]
How should getCalendarEvents, getContacts, and getLocation handle a lack of permissions? 
Options include:
- Notify caller of lack of permissions
- independently request options
- crash

**Comment by ADimeo** [comment]
hasPermission is implemented.

**Comment by Paulpanther** [comment]
@ADimeo see #13

**Comment by ADimeo** [comment]
Both getCalendarEvents and getContacts are implemented.

getLocation has to wait for a callback. The most obvious solution seems to be passing in a reference of the caller, who then implements a callback method.
