### ISSUE TITLE
MainActivity: Fetch Clues

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#16]
Fetch Clues via `StoryController#requestClues()`

**Comment by ADimeo** [comment]
How transparent should the API/local database be? Right now I'm assuming that the method should request data from the API, returning the data stored on the device if the API can't be reached. Is that assumption true?

**Comment by Paulpanther** [comment]
@ADimeo yes. This is included in #18

**Comment by Paulpanther** [comment]
About the local database. Are we using lazy init or not?

**Comment by ADimeo** [comment]
The database itself is initialised in CustomApplication. Access to the database should happen via our CustomApplication's getDaoSession() method.

Regarding the data itself, I'd load clues on application startup, and after explicit requests from the StoryController (however the StoryController makes that decision we'll decide later) . New clues are only required when the player opens the app, and overhead for those small requests is small enough that I'd advise against using push notification infrastructure.
