### ISSUE TITLE
Start Telegram bot with userID

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#2]

**Comment by ADimeo** [comment]
The code is there, I can't really test it until the bot is working in some form, since telegram hides the transferred token to the user sending.

**Comment by timgarrels** [comment]
Do you think that the app should build the telegram request?
Or should the app pull a link (in this case, a telegram bot startup link) from the API and display it to the user?

I would prefer the last one, as it demonstrates that this app/game could work without telegram but with any messenger

**Comment by ADimeo** [comment]
Done
