### ISSUE TITLE
Send Tasks and Clues with Firebase

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#28]

**Comment by timgarrels** [comment]
I thought we would use firebase solely for a "wakeup"-call api for the server, which moves call responsibility from server to app?

**Comment by Paulpanther** [comment]
Not anymore, see [https://github.com/EatingBacon/gameprog-detective-server/wiki/Firebase-API](https://github.com/EatingBacon/gameprog-detective-server/wiki/Firebase-API)
