### ISSUE TITLE
Send Telegram Bot Conversation started with Firebase

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#32]
Save in setUserConversationStarted, Remove old code in MainFragment

**Comment by timgarrels** [comment]
I thought we would use firebase solely for a "wakeup"-call api for the server, which moves call responsibility from server to app?

**Comment by timgarrels** [comment]
What is meant with "Send Telegram Bot Conversation"?

**Comment by Paulpanther** [comment]
I think this is not relevant anymore
