### ISSUE TITLE
Firebase Wake Up Call

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#37]
The following scenario was planned by @Paulpanther and @EatingBacon :

The server would send a firebase call to "wake up" the app. This was supposed to be the only call ever made to firebase to simplify api implementation on app side.
The app would react to the "wake up" by calling a bunch of server api's (such as clues, tasks, requestedBackgroundData) and perform tasks dependent on the answers.

Is this still planned? I saw multiple issues regarding firebase api endpoints.
If still planned, please specify the wakeup call somewhere, so I can implement that on server side.
If not planned anymore, please explain new behavior of app, as I then need to implement the specific calls to firebase (which you need to explain as well)

**Comment by Paulpanther** [comment]
See #28
