### ISSUE TITLE
Add simpler Location stealing method

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#39]
I would like to have a method like this: 
`DataStealer#takeLocationData(Context context): Promise<LocationData>` or
`DataStealer#takeLocationData(Context context, Consumer<LocationData>)`
which returns the current location through the Consumer or Promise.

This is required for  #29

**Comment by ADimeo** [comment]
Please see if the implemented takeLocationData method works for you.
