### ISSUE TITLE
Firebase API "Execute Tasks" should be renamed

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#43]
This endpoint is triggered by the server when new tasks are assigned to a user or the status of an already assigned task changes.
Please rename the endpoint to something more fitting.
Document the change [here](https://github.com/EatingBacon/gameprog-detective-server/wiki/Firebase-API)
Please also add a description what the endpoint exactly does (does the app expect a list of all tasks, or just the diff?)

**Comment by Paulpanther** [comment]
done
