### ISSUE TITLE
Create "resetButton"

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#44]
As a dev I want to be able to reset the progress of a user easily. Please add a "resetButton" to the App UI which calls [this](https://github.com/EatingBacon/gameprog-detective-server/wiki/API#reset-user) endpoint.

**Comment by Paulpanther** [comment]
I guess the data in the app (userid, ...) should also be deleted?

**Comment by Paulpanther** [comment]
Created `StorageManager#reset` which resets all stored data (except token)

**Comment by ADimeo** [comment]
@Paulpanther what methods should the onClick of the reset button call?

**Comment by Paulpanther** [comment]
`MainActivity#reset`
