### ISSUE TITLE
Create "ServerURL" setting

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#45]
It is my understanding that the server url is currently hard coded.
If we hand in our code the gameprog people might want to setup their own server.

As we only want to hand in the code of the app and a finished release (but no build process), we need a setting in the app to configure the backend server url

**Comment by ADimeo** [comment]
Button modifies the state of the StorageManager.
@Paulpanther is the URL dynamically taken from the StorageManager?

**Comment by Paulpanther** [comment]
Yes

**Comment by ADimeo** [comment]
With that this is done.
