### ISSUE TITLE
App crashes when Task is clicked

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#46]

**Comment by ADimeo** [comment]
During development a bug came up where the app would crash when the executable task of a task was null, this might be the same thing.

**Comment by Paulpanther** [comment]
Look at the output of the firebaseparser

**Comment by Paulpanther** [comment]
Renaming `Task#dataType` to `Task#datatype` will fix the issue. But such errors should be thrown not when clicking the task, but when the data from the server is parsed. I will implement such a check and then close this issue

**Comment by Paulpanther** [comment]
This is not implemented yet
