### ISSUE TITLE
Crash on launch in APIBUilder

### ISSUE THREAD

**Issue by ADimeo** [ADimeo/gameprog-detective-app#54]
On launch APIBuilder is fed with the url "telegram.me/AndyAbbot?start...".
This crashes the APIBuilder, since it expects something including http://

The broken url is given to APIBuilder.build by ApiService#reConnectIfUrlChange, which is launched by ApiService#onHandleIntent. I can't follow the stack trace further right now.

**Comment by Paulpanther** [comment]
It's because I'm stupid and I used the Telegram Bot Url as Server URL. Will fix it
