### ISSUE TITLE
Picture Task

### ISSUE THREAD

**Issue by Paulpanther** [ADimeo/gameprog-detective-app#60]
Based on the result of #59 implement one of the following scenarios:
1. Task: Take a picture. User clicks *fulfill*, camera opens, User takes a picture, camera closes, app opens, sends picture to server
2. Task: Upload a picture. User clicks *fulfill*, gallery opens, User selects picture, gallery closes, app opens, sends picture to server

If 1 is possible, do 1 (But it would be nice to have gallery permissions too)

**Comment by robinwersich** [comment]
how should the server interface for pictures be?
could you do an issue on the server repo?

**Comment by Paulpanther** [comment]
Check Metadata (like Location)

**Comment by robinwersich** [comment]
please have a look at the wiki again, the server interface has changed:
- the form field is called `image`, not `upload`
- the filename should have an extension
