### ISSUE TITLE
Specify TextMessage Data

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#63]
Please let me know in which format `textMessages` `timeStamp` is sent.
In which order is the datestring?

**Comment by timgarrels** [comment]
Is it possible for you to send a string like `2020-02-18 11:23:17.377352`?
`year-month-day hour:minute:second.milisecond`?
You can omit the miliseconds :D

Seconds since epoch would be fine too

**Comment by ADimeo** [comment]
AFAIK the current format is milliseconds since epoch.
If that's not the case I can recheck the code.

**Comment by robinwersich** [comment]
integers are easier to compare with sqllite anyway, but seconds instead of milliseconds would make more sense

**Comment by Paulpanther** [comment]
Fixed in #64
