### ISSUE TITLE
firebase endpoint for adding calendar events

### ISSUE THREAD

**Issue by robinwersich** [ADimeo/gameprog-detective-app#68]
it would be very cool (and spooky) if the server could ask the app to create a calendar event, so that kommissar Rex can put appointments into the users calendar. The natural way to do this is probably to add an additional optional `calendarEvents` field to task

**Comment by robinwersich** [comment]
any updates for this?

**Comment by Paulpanther** [comment]
In 10c38bd2b48a03a245b394655b39ef16e5680cc9 I tried adding calendar events, but for now I only found a method which requires the user to click on a popup. I would say we do this after the presentation

**Comment by robinwersich** [comment]
alright - but I think the creepiness factor works only without user confirmation, so if that's not possible we don't really need this feature at all

**Comment by Paulpanther** [comment]
I have not found a solution for this, so I'll close this issue
