### ISSUE TITLE
send mock data if safety mode is turned on

### ISSUE THREAD

**Issue by robinwersich** [ADimeo/gameprog-detective-app#78]
@robinwersich will provide mock data for every task that can be sent by the app if safety mode is turned on.
There should be a short text below the safety mode switch describing the current state, e.g.
for safety mode off:
```
send your personal data (over HTTP - beware!)
```

for safety mode on:
```
replace personal data with mock data (you will still need to obey time restrictions)
```

**Comment by Paulpanther** [comment]
This will not be implemented this way (See the wiki about how to send mock data)
@robinwersich I will close this since it is not relevant any longer
