### ISSUE TITLE
Please review Example Interaction WikiPage

### ISSUE THREAD

**Issue by timgarrels** [ADimeo/gameprog-detective-app#80]
[Example Interactions](https://github.com/EatingBacon/gameprog-detective-server/wiki/Example-Interactions) might be out of date
[Firebase API](https://github.com/EatingBacon/gameprog-detective-server/wiki/Firebase-API) might be out of date (clue endpoint certainly is).
[Task API](https://github.com/EatingBacon/gameprog-detective-server/wiki/Task) might be out of date. Please validate the API and pay attention to the text below (quote `then press the complete button`, is the complete button still a thing?)

pls update pages

**Comment by Paulpanther** [comment]
Updated Example Interactions

**Comment by Paulpanther** [comment]
Updated Firebase (Removed Clues, added link to code)

**Comment by Paulpanther** [comment]
And updated Task
